#pragma once
// стили для конструктора страниц GyverPortal

const char GP_DEFAULT[] PROGMEM =
"<style type=\"text/css\">\n"
"body {font-family:sans-serif;margin-top:30px;}\n"
"hr {width:90%;margin-bottom:10px;}\n"
"h2 {margin:8px 0;}\n"
"span {font-size:20px;}\n"
"label {font-size:20px;margin:0 5px;}\n"
".chartBlock {margin:10px;width:90%;height:500px}\n"
".block {border-radius:10px;background-color:#f2f2f2;padding:20px 0px;margin:10px 0;width: 90%;}\n"
"input[type=\"text\"],input[type=\"password\"],input[type=\"date\"],input[type=\"time\"],input[type=\"range\"],input[type=\"color\"],input[type=\"checkbox\"],select\n"
"{vertical-align:middle;position:relative;margin:2px 0 7px 0;font-size:20px;height:30px;cursor:pointer;}\n"
"input[type=\"range\"] {width:50%;height:35px;}\n"
"input[type=\"color\"] {width:100px;height:40px;}\n"
"input[type=\"checkbox\"] {width:30px;height:30px;margin-bottom:10px;}\n"
"input[type=\"text\"],input[type=\"password\"] {max-width:60%;}\n"
"input[type=\"submit\"],input[type=\"button\"] {height:60px;font-size:28px;width:80%;margin:8px 0;}\n"
"select {width:50%;}\n"
".switch{margin-top:10px;position:relative;display:inline-block;width:60px;height:34px}\n"
".switch input{opacity:0;width:0;height:0}\n"
".slider{border-radius:34px;position:absolute;cursor:pointer;top:0;left:0;right:0;bottom:0;background-color:#ccc;-webkit-transition:.1s;transition:.1s}\n"
".slider:before{border-radius:50%;position:absolute;content:\"\";height:26px;width:26px;left:4px;bottom:4px;background-color:#fff;-webkit-transition:.1s;transition:.1s}\n"
"input:checked+.slider{background-color:#2196f3}\n"
"input:checked+.slider:before{-webkit-transform:translateX(26px);-ms-transform:translateX(26px);transform:translateX(26px)}\n"
"</style>\n";

const char GP_LIGHT[] PROGMEM =
"<style type=\"text/css\">\n"
"body {font-family: sans-serif;margin-top:30px;}\n"
"hr {width:90%;margin-bottom:10px;}\n"
"h2 {margin:8px 0;}\n"
"span {font-size:20px;}\n"
"label {font-size:20px;margin:0 5px;}\n"
".chartBlock {margin:10px;width:90%;height:500px}\n"
".block {border-radius:10px;background-color:#f2f2f2;padding:20px 0px;margin:10px 0;width: 90%;}\n"
"input[type=\"text\"],input[type=\"password\"],input[type=\"date\"],input[type=\"time\"],input[type=\"range\"],input[type=\"color\"],input[type=\"checkbox\"],select\n"
"{padding:0 8px;vertical-align:middle;position:relative;margin:2px 0 7px 0;font-size:20px;height:38px;cursor:pointer;}\n"
"input[type=\"range\"] {width:50%;height:35px;}\n"
"input[type=\"color\"] {width:100px;height:40px;border-radius:5px;}\n"
"input[type=\"checkbox\"] {width:30px;height:30px;margin-bottom:10px;}\n"
"input[type=\"text\"],input[type=\"password\"],select {max-width:60%;display:inline-block;border:1px solid #ccc;border-radius:6px;box-sizing:border-box;cursor:auto;}\n"
"input[type=\"submit\"],input[type=\"button\"] {height:60px;font-size:28px;width:80%;margin:8px 0;background-color:#4CAF50;border:none;border-radius:6px;color:white;cursor:pointer;}\n"
"input[type=submit],input[type=\"button\"]:hover {background-color:#45a049;}\n"
".led {margin:10px 18px;}\n"
".led:after {width:25px;height:25px;border-radius:25px;top:-10px;left:-9px;position:relative;content:'';display:inline-block;border:2px solid;border-color:#858585;background-color:#323232}\n"
".led:checked:after {box-shadow:0px 0px 10px;}\n"
".led.red:checked:after {border-color:red !important;color:red !important;background-color:red !important;}\n"
".led.green:checked:after {border-color:lime !important;color:lime !important;background-color:lime !important;}\n"
"select {width:50%;}\n"
".switch{margin-top:10px;position:relative;display:inline-block;width:60px;height:34px}\n"
".switch input{opacity:0;width:0;height:0}\n"
".slider{border-radius:34px;position:absolute;cursor:pointer;top:-5px;left:0;right:0;bottom:5px;background-color:#ccc;-webkit-transition:.1s;transition:.1s}\n"
".slider:before{border-radius:50%;position:absolute;content:\"\";height:26px;width:26px;left:4px;bottom:4px;background-color:#fff;-webkit-transition:.1s;transition:.1s}\n"
"input:checked+.slider{background-color:#2196f3}\n"
"input:checked+.slider:before{-webkit-transform:translateX(26px);-ms-transform:translateX(26px);transform:translateX(26px)}\n"
"</style>\n";

const char GP_DARK[] PROGMEM =
"<style type=\"text/css\">\n"
"#blockBack>input[type=\"password\"]{background:#161A1E}\n"
"#blockBack>input[type=\"text\"]{background:#161A1E}\n"
"#blockBack>input[type=\"date\"]{background:#161A1E}\n"
"#blockBack>input[type=\"time\"]{background:#161A1E}\n"
"#blockBack>select{background:#161A1E}\n"
"body {font-family: sans-serif;background:#161A1E;color:#bbb;margin-top:30px;}\n"
"hr {width:90%;margin-bottom:10px;border:none;border-top:2px solid #394048;}\n"
"h2 {margin:8px 0;}\n"
"span {font-size:20px;}\n"
"label {font-size:20px;margin:0 5px;}\n"
".chartBlock {margin:10px;width:90%;height:500px}\n"
".block {border-radius:10px;background-color:#2a2d35;padding:20px 0px;margin:10px 0;width: 90%;}\n"
"input[type=\"text\"],input[type=\"password\"],input[type=\"date\"],input[type=\"time\"],input[type=\"range\"],input[type=\"color\"],input[type=\"checkbox\"],select\n"
"{padding:0 8px;color:#bbb;border:none;background-color:#2a2d35;vertical-align:middle;position:relative;margin:2px 0 7px 0;font-size:20px;height:38px;cursor:pointer;}\n"
"input[type=\"range\"] {width:50%;height:35px;}\n"
"input[type=\"color\"] {width:100px;height:40px;border-radius:5px;}\n"
"input[type=\"checkbox\"] {width:30px;height:30px;margin-bottom:10px;}\n"
"input[type=\"text\"],input[type=\"password\"],select {max-width:60%;display:inline-block;border-radius:6px;box-sizing:border-box;cursor:auto;}\n"
"input[type=\"submit\"],input[type=\"button\"] {height:60px;font-size:28px;width:80%;margin:8px 0;background-color:#4CAF50;border:none;border-radius:6px;color:white;cursor:pointer;}\n"
"input[type=submit],input[type=\"button\"]:hover {background-color:#45a049;}\n"
"input:focus,select:focus{outline:none;}"
".led {margin:10px 18px;}\n"
".led:after {width:25px;height:25px;border-radius:25px;top:-10px;left:-9px;position:relative;content:'';display:inline-block;border:2px solid;border-color:#858585;background-color:#121212}\n"
".led:checked:after {box-shadow:0px 0px 10px 4px;}\n"
".led.red:checked:after {border-color:red !important;color:red !important;background-color:red !important;}\n"
".led.green:checked:after {border-color:lime !important;color:lime !important;background-color:lime !important;}\n"
"select {width:50%;}\n"
".switch{margin-top:10px;position:relative;display:inline-block;width:60px;height:34px}\n"
".switch input{opacity:0;width:0;height:0}\n"
".slider{border-radius:34px;position:absolute;cursor:pointer;top:-5px;left:0;right:0;bottom:5px;background-color:#54545485;-webkit-transition:.1s;transition:.1s}\n"
".slider:before{border-radius:50%;position:absolute;content:\"\";height:26px;width:26px;left:4px;bottom:4px;background-color:#fff;-webkit-transition:.1s;transition:.1s}\n"
"input:checked+.slider{background-color:#2196f3}\n"
"input:checked+.slider:before{-webkit-transform:translateX(26px);-ms-transform:translateX(26px);transform:translateX(26px)}\n"
"</style>\n";